### ISSUE TITLE
Comparison with Scrapy

### ISSUE THREAD

**Issue by Vanuan** [sunlightlabs/scrapelib#30]
I couldn't find any comparison with a more popular [scrapy](http://scrapy.org/) library.
I see that Scrapy is [much older](https://github.com/scrapy/scrapy/commits/master?page=120) than scrapelib.
Could you please provide key advantages of scrapelib over Scrapy?

**Comment by jamesturk** [comment]
the intent of this library is much different than Scrapy- scrapy is more of a framework, this is a library similar to requests (in fact it is really just a set of enhancements to requests)- it does less but is more flexible in how you deal with responses
