### ISSUE TITLE
scrapelib incorrectly caches kwargs to requests

### ISSUE THREAD

**Issue by konklone** [sunlightlabs/scrapelib#31]
I initialized a scraper, and fetched a URL whose server has not correctly configured their HTTPS certificates. (They're missing the intermediates, so desktop browsers will fetch them, but most client libs will not.)

```python
scraper.get("https://www.ignet.gov/sites/default/files/files/Cloud%20Computing%20Initiative%20Report.pdf")
```

This hangs, as it goes through a retry cycle, and will eventually fail. If I pass the `verify=False` option, as [documented in `requests`](http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification), it will work and spit out a warning:

```python
scraper.get("https://www.ignet.gov/sites/default/files/files/Cloud%20Computing%20Initiative%20Report.pdf", verify=False)

/home/eric/.virtualenvs/inspectors/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

```

However, if I then remove the `verify` flag, _or even if I add it back_ with `verify=True`, I can't coax scrapelib into going back into verify mode:

```python
scraper.get("https://www.ignet.gov/sites/default/files/files/Cloud%20Computing%20Initiative%20Report.pdf", verify=True)

/home/eric/.virtualenvs/inspectors/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

Raw `requests.get()` calls do not display this behavior. So, something in scrapelib's caching behavior is caching keyword options.

To be clear, I think the correct behavior here is not to cache kwargs at all, as I wouldn't want `verify` to "stick" whether or not I was explicit about it later.

This is with the latest version of scrapelib:

```
requests==2.5.1
scrapelib==0.10.1
```

**Comment by jamesturk** [comment]
thanks.  interesting issue, I'll think about how to best handle it.  probably will need to figure out how to invalidate the cache when a kwarg is provided

**Comment by konklone** [comment]
I think that's not the only issue. The problem I observed was that once I had passed in `verify=False`, that flag "stuck" for all future requests -- even different URLs.

I would want the `kwargs` to invalidate the cache too, so that I could re-run the same URL but flip `verify` from `False` to `True`. But in practice, I'd be a lot better off if even the URL reliably invalidated cached kwargs.

**Comment by jamesturk** [comment]
That's really odd sounding, think you might be able to provide a snippet
that does this?

Sounds like it might have to do w/ requests (as those parameters are just
passthroughs) but I'll dig into it.

On Thu, Feb 5, 2015 at 10:58 PM, Eric Mill <notifications@github.com> wrote:

> I think that's not the only issue. The problem I observed was that once I
> had passed in verify=False, that flag "stuck" for all future requests --
> even different URLs.
>
> I would want the kwargs to invalidate the cache too, so that I could
> re-run the same URL but flip verify from False to True. But in practice,
> I'd be a lot better off if even the URL reliably invalidated cached kwargs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunlightlabs/scrapelib/issues/31#issuecomment-73179390>
> .
>



-- 

James Turk
Labs Director | Sunlight Foundation <http://www.sunlightfoundation.com/>
202-558-8723 | @JamesTurk <https://twitter.com/jamesturk>

[image: Sunlight Foundation] <http://sunlightfoundation.com/>

**Comment by konklone** [comment]
Here's a snippet that shows this:

```python
import scrapelib
scraper = scrapelib.Scraper(requests_per_minute=120, retry_attempts=3)
scraper.user_agent = "unitedstates/inspectors-general (https://github.com/unitedstates/inspectors-general)"

scraper.get("https://www.ignet.gov/sites/default/files/files/Cloud%20Computing%20Initiative%20Report.pdf")
```

This hangs because it, correctly cannot establish a verified HTTPS connection. I hit Ctrl-C and continue:

```python
scraper.get("https://www.ignet.gov/sites/default/files/files/Cloud%20Computing%20Initiative%20Report.pdf", verify=False)
```

This works, but correctly throws a warning that it was an insecure connection:

```
/home/eric/.virtualenvs/inspectors/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

Now if I make another request to a different URL, without sending a `verify` flag (and so it should verify the connection by default):

```python
scraper.get("https://www.ignet.gov")
```

It incorrectly continues to not verify the connection:

```
/home/eric/.virtualenvs/inspectors/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

However, `requests` behaves correctly. It throws a verification error upon the first call:

```python
requests.get("https://www.ignet.gov/sites/default/files/files/Cloud%20Computing%20Initiative%20Report.pdf")
```

```
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
```

I can disable verification with the same kwargs flag, which works and warns about the connection:

```python
requests.get("https://www.ignet.gov/sites/default/files/files/Cloud%20Computing%20Initiative%20Report.pdf", verify=False)
```

```
/home/eric/.virtualenvs/inspectors/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

But then if I send it another URL, and remove the `verify` flag so that it defaults to verification, it correctly continues to enforce verification:

```python
requests.get("https://www.ignet.gov")
```

```
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:598)
```

So there's an issue in scrapelib somewhere -- it feels like it's incorrectly caching kwargs, even when the URL changes.

Also, I'm not sure why scrapelib's and requests' behavior differs when making a request to an unverified connection. `scrapelib` hangs, `requests` immediately throws a verification error.

**Comment by jamesturk** [comment]
Do you have another URL handy that verification should fail on?  I think I've traced the bug back to requests.Session- but it might be intended behavior.

**Comment by jamesturk** [comment]
Ha found one (thanks to a bad varnish rule on our end)

```
import scrapelib
import requests
scraper = scrapelib.Scraper(requests_per_minute=120, retry_attempts=3)
scraper.get("https://www.ignet.gov/sites/default/files/files/Cloud%20Computing%20Initiative%20Report.pdf", verify=False)
scraper.get("https://www.ignet.gov")

s = requests.Session()
s.get("https://www.ignet.gov/sites/default/files/files/Cloud%20Computing%20Initiative%20Report.pdf", verify=False)
s.get("https://www.ignet.gov")
s.get("https://www.capitolwords.org")
```


requests.Session() stores some SSL state (it is what scrapelib is based upon)- in both cases the second call to ignet.gov succeeds w/ a warning.  if you call a different domain (therefore different cert/etc.) it does fail though

I'm going to consider this OK, it makes sense that if you choose not to verify a cert on one domain you aren't worried if future requests to the same domain don't verify either.  Since the verify flag isn't sticky beyond a single domain it shouldn't cause real problems.

As for the hanging vs. immediate failure, that was because SSLErrors were triggering a retry, I've fixed that.

**Comment by konklone** [comment]
Got it. I didn't try `requests.Session`. I actually don't think `requests`' behavior is the correct one and that it should only cache per-URL, though I understand why they might feel per-domain is better. But in any case, knowing it's a `requests` issue solves it for me. 

Thanks for looking into this, and fixing the hanging issue!
